version: '3.8'
services:
  service-cliente:
    build:
      context: ./cliente
      dockerfile: Dockerfile
    ports:
      - "8081:8081"
    environment:
      - DB_HOST=db
      - DB_PASS=Admin@1234
      - SERVICE_PORT=8081
    depends_on:
      - db

  service-cuentas:
    build:
      context: ./cuenta
      dockerfile: Dockerfile
    ports:
      - "8082:8082"
    environment:
      - DB_HOST=db
      - DB_PASS=Admin@1234
      - SERVICE_PORT=8082
      - CLIENTE_SERVICE_URL=localhost
      - CLIENTE_SERVICE_PORT=8081
    depends_on:
      - service-cliente
  db:
    image: mcr.microsoft.com/mssql/server:2019-latest
    environment:
      MSSQL_SA_PASSWORD: Admin@1234
      ACCEPT_EULA: "Y"
      MSSQL_PID: Express
    ports:
      - "1433:1433"
    volumes:
      - sqlserver-data:/var/opt/mssql

volumes:
  sqlserver-data: